version: '3.9'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KUMULUZEE_ENV_NAME=${ENVIRONMENT}
      - KUMULUZEE_NAME=${MICROSERVICE_NAME}
      - KUMULUZEE_SERVER_HTTP_PORT=${LOCAL_PORT}
      - KUMULUZEE_DATASOURCES0_USERNAME=${POSTGRES_USER}
      - KUMULUZEE_DATASOURCES0_PASSWORD=${POSTGRES_PASSWORD}
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - KUMULUZEE_CONFIG_CONSUL_AGENT=${CONSUL_URL}
      - KUMULUZEE_RESTCLIENT_REGISTRATIONS0_URL=${REST_CLIENT_MAIL}
    ports:
      - ${LOCAL_PORT}:${LOCAL_PORT}

networks:
  default:
    name: rso
    external: true
